name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /root/SigmaMed
          git config pull.rebase false
          git reset --hard HEAD
          git clean -fd
          git fetch origin
          git reset --hard origin/main
          docker-compose down
          docker-compose up -d --build
          sleep 15
          docker exec sigmamed_backend_1 npx prisma migrate deploy
          docker exec sigmamed_backend_1 npx prisma generate
          echo "Deployment completed at $(date)"