name: Deploy to Server

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /root/SigmaMed
          
          # Остановить контейнеры и очистить место
          docker-compose down || true
          docker system prune -a -f || true
          docker builder prune -a -f || true
          
          # Обновить код (без интерактивного ввода)
          git config pull.rebase false
          git reset --hard HEAD
          git clean -fd
          git reset --hard origin/main || git reset --hard HEAD
          
          # Проверить место на диске
          df -h
          
          # Запустить контейнеры
          docker-compose up -d --build
          sleep 20
          
          # Выполнить миграции если backend контейнер запустился
          if docker ps | grep -q sigmamed_backend; then
            docker exec sigmamed_backend_1 npx prisma migrate deploy || true
            docker exec sigmamed_backend_1 npx prisma generate || true
          fi
          
          echo "Deployment completed at $(date)"